# Funding Configuration - Stub Generator
# Uncomment and configure the platforms you want to use

# github: [pixielity-co]
# patreon: pixielity
# open_collective: stub-generator
# ko_fi: pixielity
# custom: ['https://pixielity.co/sponsor']
